#!/usr/bin/env python3
"""
End-to-end test suite for the netcore-lldb client tool.

Runs the client against two real targets:
  1. A docker container (started fresh, has lldb + SOS + the dump)
  2. SSH to localhost (WSL has lldb + SOS; the dump is on the WSL filesystem)

For each, the suite exercises:
  - argument parsing / mutually-exclusive transports
  - preflight checks (unreachable target, missing lldb, missing dump)
  - MCP protocol (initialize, tools/list, ping, shutdown, unknown method)
  - tool dispatch (unknown tool, bad arguments, normal call)
  - SOS command coverage (eeversion, clrthreads, pe, clrstack with source lines,
    dumpheap -stat, clrmodules)
  - stateful session (thread select, then clrstack on that thread)
  - --copy-dump (pushes a local dump to the target before opening lldb)

Test names are tagged [docker] / [ssh] / [common].

Exit code: 0 if all pass, 1 if any fail. Prints a summary at the end.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
import time

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
CLIENT = os.path.join(ROOT, "client", "netcore_lldb.py")
DUMP_LOCAL = sorted(
    [os.path.join(ROOT, "dumps", f) for f in os.listdir(os.path.join(ROOT, "dumps"))
     if re.match(r"crasher\.\d+\.dmp", f)],
    key=os.path.getmtime, reverse=True
)[0]
APP_LOCAL = os.path.join(ROOT, "sample", "out")

CONTAINER = "netcore-lldb-tests"
SSH_HOST = "cad@127.0.0.1"

# Curated dumps generated by tests/fixtures/build-and-dump.sh. Each exercises
# one Tess Ferrandez playbook end-to-end (one symptom → one expected SOS
# finding). The dumps live on the WSL filesystem; their recorded paths line up
# with where they were built, so SSH transport finds everything natively.
FIXTURES_DIR = os.path.join(ROOT, "tests", "fixtures")
DUMPS_OUT_DIR = os.path.join(ROOT, "tests", "dumps")
FIXTURES = {
    "memory-leak": {
        "dump": os.path.join(DUMPS_OUT_DIR, "memory-leak.dmp"),
        "exec": os.path.join(FIXTURES_DIR, "memory-leak", "out", "MemoryLeak"),
    },
    "deadlock": {
        "dump": os.path.join(DUMPS_OUT_DIR, "deadlock.dmp"),
        "exec": os.path.join(FIXTURES_DIR, "deadlock", "out", "Deadlock"),
    },
    "event-handler-leak": {
        "dump": os.path.join(DUMPS_OUT_DIR, "event-handler-leak.dmp"),
        "exec": os.path.join(FIXTURES_DIR, "event-handler-leak", "out", "EventHandlerLeak"),
    },
}

results: list[tuple[str, bool, str]] = []


def msg(method: str, **params) -> dict:
    m = {"jsonrpc": "2.0", "method": method, "id": params.pop("_id", 1)}
    if params:
        m["params"] = params
    return m


def notif(method: str, **params) -> dict:
    m = {"jsonrpc": "2.0", "method": method}
    if params:
        m["params"] = params
    return m


def initialize_seq() -> list[dict]:
    return [
        {"jsonrpc": "2.0", "id": 1, "method": "initialize",
         "params": {"protocolVersion": "2024-11-05", "capabilities": {}, "clientInfo": {"name": "t", "version": "0"}}},
        {"jsonrpc": "2.0", "method": "notifications/initialized"},
    ]


def drive(args: list[str], messages: list[dict], timeout: float = 90.0) -> tuple[list[dict], str, int]:
    """Spawn the client, send messages, return (responses, stderr, rc)."""
    proc = subprocess.Popen(
        [sys.executable, CLIENT] + args,
        stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
        text=True,
    )
    inp = "\n".join(json.dumps(m) for m in messages) + "\n"
    try:
        out, err = proc.communicate(input=inp, timeout=timeout)
    except subprocess.TimeoutExpired:
        proc.kill()
        out, err = proc.communicate()
        return [], err, -1
    responses = [json.loads(ln) for ln in out.splitlines() if ln.strip()]
    return responses, err, proc.returncode


def find_response(responses: list[dict], msg_id) -> dict | None:
    for r in responses:
        if r.get("id") == msg_id:
            return r
    return None


def text_of(resp: dict) -> str:
    return resp.get("result", {}).get("content", [{}])[0].get("text", "")


def record(name: str, ok: bool, note: str = "") -> None:
    results.append((name, ok, note))
    mark = "PASS" if ok else "FAIL"
    color = "\033[32m" if ok else "\033[31m"
    print(f"  {color}{mark}\033[0m  {name}{(' — ' + note) if note else ''}")


# ============================================================================
# Setup / teardown
# ============================================================================

def docker_run(*a, **kw):
    return subprocess.run(["docker"] + list(a), capture_output=True, text=True, **kw)


def setup_docker_target() -> None:
    print("  setup_docker_target: rm prior...", flush=True)
    subprocess.run(["docker", "rm", "-f", CONTAINER], capture_output=True, timeout=30)
    print("  setup_docker_target: starting container...", flush=True)
    rc = subprocess.call([
        "docker", "run", "-d", "--name", CONTAINER,
        "-v", "/usr/lib/dotnet:/usr/lib/dotnet:ro",
        "--entrypoint", "sleep", "netcore-lldb:dev", "infinity"
    ], stdout=subprocess.DEVNULL, timeout=60)
    if rc != 0:
        raise SystemExit("could not start docker target container")
    print("  setup_docker_target: copying dump...", flush=True)
    subprocess.run(["docker", "cp", DUMP_LOCAL, f"{CONTAINER}:/work/dump.core"], check=True, timeout=60)
    print("  setup_docker_target: mkdir app...", flush=True)
    subprocess.run(["docker", "exec", CONTAINER, "mkdir", "-p", "/work/app"], check=True, timeout=30)
    print("  setup_docker_target: copying app dir...", flush=True)
    subprocess.run(["docker", "cp", f"{APP_LOCAL}/.", f"{CONTAINER}:/work/app/"], check=True, timeout=60)
    # Symlink the dump's recorded exe path to /work/app so lldb auto-loads it.
    print("  setup_docker_target: setting up dump-recorded-path symlinks...", flush=True)
    subprocess.run([
        "docker", "exec", CONTAINER, "bash", "-c",
        'RECORDED=$(strings /work/dump.core | grep -oE "^/[^[:space:]]+/Crasher$" | head -1 || true); '
        '[ -n "$RECORDED" ] && mkdir -p "$(dirname $RECORDED)" && '
        'for f in /work/app/*; do ln -sf "$f" "$(dirname $RECORDED)/$(basename $f)"; done'
    ], check=False, timeout=30)
    print("  setup_docker_target: done.", flush=True)


def setup_ssh_target() -> None:
    # The ssh target is WSL itself (cad@127.0.0.1). DUMP_LOCAL on the
    # Windows-mounted filesystem is reachable directly from WSL — the dump's
    # recorded paths (/mnt/c/.../sample/out/Crasher) ARE valid on WSL because
    # /mnt/c is the Windows mount. We stage copies under /tmp/netcore-lldb-test/
    # for the client to point at, but we deliberately DO NOT create symlinks
    # at the dump-recorded path because that would clobber the real source dir.
    print("  setup_ssh_target: sshing in to stage dump and app...", flush=True)
    ssh_cmd = [
        "ssh", "-o", "BatchMode=yes", "-o", "ConnectTimeout=5",
        "-i", "/home/cad/.ssh/netcore-lldb-test_ed25519",
        SSH_HOST,
        'rm -rf /tmp/netcore-lldb-test && mkdir -p /tmp/netcore-lldb-test/app && '
        'cp -r ' + APP_LOCAL + '/. /tmp/netcore-lldb-test/app/ && '
        'cp ' + DUMP_LOCAL + ' /tmp/netcore-lldb-test/dump.core'
    ]
    try:
        subprocess.run(ssh_cmd, check=False, timeout=60, capture_output=True)
        print("  setup_ssh_target: done.", flush=True)
    except subprocess.TimeoutExpired:
        print("  setup_ssh_target: SSH staging TIMED OUT — ssh tests will fail", flush=True)


def teardown_docker_target() -> None:
    docker_run("rm", "-f", CONTAINER)


# ============================================================================
# Tests — argument / preflight (no target required, or per-test target)
# ============================================================================

def test_args_no_transport():
    name = "[common] argparse: no transport flag rejected"
    proc = subprocess.run([sys.executable, CLIENT, "--dump", "/x"],
                          capture_output=True, text=True)
    ok = proc.returncode != 0 and "--docker" in proc.stderr and "--ssh" in proc.stderr
    record(name, ok, f"stderr first line: {proc.stderr.splitlines()[0][:80] if proc.stderr else ''}")


def test_args_both_transports():
    name = "[common] argparse: --docker and --ssh both rejected"
    proc = subprocess.run([sys.executable, CLIENT, "--docker", "x", "--ssh", "y", "--dump", "/x"],
                          capture_output=True, text=True)
    ok = proc.returncode != 0 and ("not allowed" in proc.stderr or "mutually exclusive" in proc.stderr.lower())
    record(name, ok)


def test_args_missing_dump():
    name = "[common] argparse: missing --dump rejected"
    proc = subprocess.run([sys.executable, CLIENT, "--docker", "x"],
                          capture_output=True, text=True)
    ok = proc.returncode != 0 and "--dump" in proc.stderr
    record(name, ok)


def test_args_copy_dump_local_missing():
    name = "[common] --copy-dump with missing local file fails fast"
    responses, err, rc = drive(
        ["--docker", CONTAINER, "--dump", "/tmp/does-not-exist.dmp", "--copy-dump"],
        initialize_seq(), timeout=30
    )
    ok = rc != 0 and "missing local file" in err
    record(name, ok, f"rc={rc}")


def test_preflight_bad_container():
    name = "[docker] preflight: unreachable container errors clearly"
    responses, err, rc = drive(
        ["--docker", "this-container-does-not-exist", "--dump", "/x"],
        initialize_seq(), timeout=30
    )
    ok = rc != 0 and "could not reach target" in err
    record(name, ok)


def test_preflight_bad_ssh():
    name = "[ssh] preflight: unreachable ssh host errors clearly"
    responses, err, rc = drive(
        ["--ssh", "nobody@nonexistent.invalid.example", "--dump", "/x"],
        initialize_seq(), timeout=30
    )
    ok = rc != 0 and "could not reach target" in err
    record(name, ok)


def test_preflight_no_lldb():
    name = "[docker] preflight: target without lldb errors clearly"
    bare = "netcore-lldb-bare-test"
    docker_run("rm", "-f", bare)
    subprocess.call(["docker", "run", "-d", "--name", bare, "--entrypoint", "sleep",
                     "ubuntu:24.04", "infinity"], stdout=subprocess.DEVNULL)
    try:
        responses, err, rc = drive(
            ["--docker", bare, "--dump", "/etc/hostname"],  # any existing file as dump placeholder
            initialize_seq(), timeout=30
        )
        ok = rc != 0 and "does not have" in err and "lldb" in err
        record(name, ok)
    finally:
        docker_run("rm", "-f", bare)


def test_preflight_missing_dump():
    name = "[docker] preflight: missing dump on target errors clearly"
    responses, err, rc = drive(
        ["--docker", CONTAINER, "--dump", "/nope/missing.core"],
        initialize_seq(), timeout=30
    )
    ok = rc != 0 and "does not exist on target" in err
    record(name, ok)


# ============================================================================
# Tests — MCP protocol (run against working docker target)
# ============================================================================

COMMON_ARGS = ["--docker", CONTAINER, "--dump", "/work/dump.core", "--exec", "/work/app/Crasher"]


def test_mcp_initialize():
    name = "[common] initialize returns serverInfo + instructions"
    msgs = initialize_seq()
    responses, err, rc = drive(COMMON_ARGS, msgs)
    r = find_response(responses, 1)
    ok = (r and r.get("result", {}).get("serverInfo", {}).get("name") == "netcore-lldb"
          and len(r["result"].get("instructions", "")) > 100
          and "tools" in r["result"].get("capabilities", {}))
    record(name, bool(ok))


def test_mcp_tools_list():
    name = "[common] tools/list returns expected tools"
    msgs = initialize_seq() + [{"jsonrpc": "2.0", "id": 2, "method": "tools/list"}]
    responses, _, _ = drive(COMMON_ARGS, msgs)
    r = find_response(responses, 2)
    tools = r and {t["name"] for t in r.get("result", {}).get("tools", [])}
    ok = tools == {"lldb_command", "target_info"}
    record(name, bool(ok), f"tools={tools}")


def test_mcp_ping():
    name = "[common] ping returns empty result"
    msgs = initialize_seq() + [{"jsonrpc": "2.0", "id": 2, "method": "ping"}]
    responses, _, _ = drive(COMMON_ARGS, msgs)
    r = find_response(responses, 2)
    ok = r and r.get("result") == {}
    record(name, bool(ok))


def test_mcp_unknown_method():
    name = "[common] unknown method returns -32601"
    msgs = initialize_seq() + [{"jsonrpc": "2.0", "id": 2, "method": "no/such/method"}]
    responses, _, _ = drive(COMMON_ARGS, msgs)
    r = find_response(responses, 2)
    ok = r and r.get("error", {}).get("code") == -32601
    record(name, bool(ok))


def test_mcp_unknown_tool():
    name = "[common] tools/call unknown tool returns isError"
    msgs = initialize_seq() + [{"jsonrpc": "2.0", "id": 2, "method": "tools/call",
                                "params": {"name": "no_such_tool", "arguments": {}}}]
    responses, _, _ = drive(COMMON_ARGS, msgs)
    r = find_response(responses, 2)
    ok = r and r.get("result", {}).get("isError") is True
    record(name, bool(ok))


def test_mcp_bad_command_arg():
    name = "[common] lldb_command with empty command returns isError"
    msgs = initialize_seq() + [{"jsonrpc": "2.0", "id": 2, "method": "tools/call",
                                "params": {"name": "lldb_command", "arguments": {"command": ""}}}]
    responses, _, _ = drive(COMMON_ARGS, msgs)
    r = find_response(responses, 2)
    ok = r and r.get("result", {}).get("isError") is True
    record(name, bool(ok))


# ============================================================================
# Tests — MCP resources (Phase 1)
# ============================================================================

def test_mcp_initialize_advertises_resources_and_prompts():
    name = "[common] initialize advertises tools + resources + prompts capabilities"
    msgs = initialize_seq()
    responses, _, _ = drive(COMMON_ARGS, msgs)
    r = find_response(responses, 1)
    caps = (r or {}).get("result", {}).get("capabilities", {})
    ok = (set(caps.keys()) >= {"tools", "resources", "prompts"}
          and caps.get("resources", {}).get("listChanged") is True
          and caps.get("prompts", {}).get("listChanged") is True)
    record(name, ok, f"capabilities keys: {sorted(caps.keys())}")


def test_resources_list_returns_playbooks_and_state():
    name = "[common] resources/list returns playbooks + live state resources"
    msgs = initialize_seq() + [{"jsonrpc": "2.0", "id": 2, "method": "resources/list"}]
    responses, _, _ = drive(COMMON_ARGS, msgs)
    r = find_response(responses, 2)
    uris = {x["uri"] for x in (r or {}).get("result", {}).get("resources", [])}
    expected = {
        "netcore-lldb://playbook/crash",
        "netcore-lldb://playbook/memory",
        "netcore-lldb://playbook/hang",
        "netcore-lldb://playbook/high-cpu",
        "netcore-lldb://playbook/finalizer",
        "netcore-lldb://playbook/async",
        "netcore-lldb://session",
        "netcore-lldb://modules",
        "netcore-lldb://threads",
        "netcore-lldb://heuristics",
        "netcore-lldb://known-issues",
    }
    missing = expected - uris
    ok = not missing
    record(name, ok, f"missing: {missing or '(none)'}")


def test_resources_read_playbook_crash():
    name = "[common] resources/read on a playbook returns text/markdown content"
    msgs = initialize_seq() + [
        {"jsonrpc": "2.0", "id": 2, "method": "resources/read",
         "params": {"uri": "netcore-lldb://playbook/crash"}}
    ]
    responses, _, _ = drive(COMMON_ARGS, msgs)
    r = find_response(responses, 2)
    contents = (r or {}).get("result", {}).get("contents", [])
    ok = (len(contents) == 1
          and contents[0]["uri"] == "netcore-lldb://playbook/crash"
          and contents[0]["mimeType"] == "text/markdown"
          and "pe -nested" in contents[0]["text"]
          and "clrstack -a" in contents[0]["text"])
    record(name, ok)


def test_resources_read_session_returns_json():
    name = "[common] resources/read on netcore-lldb://session returns valid JSON"
    msgs = initialize_seq() + [
        {"jsonrpc": "2.0", "id": 2, "method": "resources/read",
         "params": {"uri": "netcore-lldb://session"}}
    ]
    responses, _, _ = drive(COMMON_ARGS, msgs)
    r = find_response(responses, 2)
    contents = (r or {}).get("result", {}).get("contents", [])
    if not contents or contents[0].get("mimeType") != "application/json":
        record(name, False, f"got: {contents}")
        return
    try:
        data = json.loads(contents[0]["text"])
    except Exception as exc:
        record(name, False, f"json parse failed: {exc}")
        return
    ok = ("transport" in data and "lldb_version" in data and "dump_path" in data)
    record(name, ok, f"keys: {sorted(data.keys())}")


def test_resources_read_modules_runs_clrmodules():
    name = "[docker] resources/read netcore-lldb://modules invokes SOS clrmodules"
    msgs = initialize_seq() + [
        {"jsonrpc": "2.0", "id": 2, "method": "resources/read",
         "params": {"uri": "netcore-lldb://modules"}}
    ]
    responses, _, _ = drive(COMMON_ARGS, msgs, timeout=120)
    r = find_response(responses, 2)
    contents = (r or {}).get("result", {}).get("contents", [])
    text = contents[0]["text"] if contents else ""
    ok = "System.Private.CoreLib" in text
    record(name, ok, f"len(text)={len(text)}")


def test_resources_read_threads_runs_clrthreads():
    name = "[docker] resources/read netcore-lldb://threads invokes SOS clrthreads"
    msgs = initialize_seq() + [
        {"jsonrpc": "2.0", "id": 2, "method": "resources/read",
         "params": {"uri": "netcore-lldb://threads"}}
    ]
    responses, _, _ = drive(COMMON_ARGS, msgs, timeout=120)
    r = find_response(responses, 2)
    contents = (r or {}).get("result", {}).get("contents", [])
    text = contents[0]["text"] if contents else ""
    ok = ("InvalidOperationException" in text and "ThreadCount:" in text)
    record(name, ok, f"len(text)={len(text)}")


def test_resources_read_unknown_uri_returns_invalid_params():
    name = "[common] resources/read on unknown uri returns JSON-RPC -32602"
    msgs = initialize_seq() + [
        {"jsonrpc": "2.0", "id": 2, "method": "resources/read",
         "params": {"uri": "netcore-lldb://no-such-resource"}}
    ]
    responses, _, _ = drive(COMMON_ARGS, msgs)
    r = find_response(responses, 2)
    err = (r or {}).get("error", {})
    ok = err.get("code") == -32602 and "unknown resource" in err.get("message", "").lower()
    record(name, ok, f"error: {err}")


# ============================================================================
# Tests — MCP prompts (Phase 2)
# ============================================================================

def test_prompts_list_returns_scenario_prompts():
    name = "[common] prompts/list returns analyze-* prompts + overview"
    msgs = initialize_seq() + [{"jsonrpc": "2.0", "id": 2, "method": "prompts/list"}]
    responses, _, _ = drive(COMMON_ARGS, msgs)
    r = find_response(responses, 2)
    names = {p["name"] for p in (r or {}).get("result", {}).get("prompts", [])}
    expected = {"analyze-crash", "analyze-memory", "analyze-hang",
                "analyze-high-cpu", "analyze-finalizer", "analyze-async",
                "overview"}
    missing = expected - names
    ok = not missing
    record(name, ok, f"missing: {missing or '(none)'}")


def test_prompts_get_analyze_memory_references_memory_playbook():
    name = "[common] prompts/get analyze-memory returns a message referencing the memory playbook"
    msgs = initialize_seq() + [
        {"jsonrpc": "2.0", "id": 2, "method": "prompts/get",
         "params": {"name": "analyze-memory", "arguments": {"user_description": "RSS climbing fast"}}}
    ]
    responses, _, _ = drive(COMMON_ARGS, msgs)
    r = find_response(responses, 2)
    result = (r or {}).get("result", {})
    messages = result.get("messages", [])
    text = ""
    if messages:
        c = messages[0].get("content", {})
        text = c.get("text", "") if isinstance(c, dict) else ""
    ok = ("netcore-lldb://playbook/memory" in text
          and "RSS climbing fast" in text
          and result.get("description"))
    record(name, ok, f"text head: {text[:120]!r}")


def test_prompts_get_overview_no_playbook():
    name = "[common] prompts/get overview returns a generic kickoff (no specific playbook)"
    msgs = initialize_seq() + [
        {"jsonrpc": "2.0", "id": 2, "method": "prompts/get",
         "params": {"name": "overview", "arguments": {}}}
    ]
    responses, _, _ = drive(COMMON_ARGS, msgs)
    r = find_response(responses, 2)
    text = ""
    msgs_out = (r or {}).get("result", {}).get("messages", [])
    if msgs_out:
        c = msgs_out[0].get("content", {})
        text = c.get("text", "") if isinstance(c, dict) else ""
    ok = ("quick overview" in text.lower()
          and "eeversion" in text
          and "playbook/" not in text)  # no specific playbook referenced
    record(name, ok, f"text head: {text[:120]!r}")


def test_prompts_get_unknown_returns_invalid_params():
    name = "[common] prompts/get unknown name returns JSON-RPC -32602"
    msgs = initialize_seq() + [
        {"jsonrpc": "2.0", "id": 2, "method": "prompts/get",
         "params": {"name": "no-such-prompt", "arguments": {}}}
    ]
    responses, _, _ = drive(COMMON_ARGS, msgs)
    r = find_response(responses, 2)
    err = (r or {}).get("error", {})
    ok = err.get("code") == -32602 and "unknown prompt" in err.get("message", "").lower()
    record(name, ok, f"error: {err}")


# ============================================================================
# Tests — SOS commands via docker exec
# ============================================================================

def sos_check(name: str, args: list[str], command: str, expected_substring: str):
    msgs = initialize_seq() + [
        {"jsonrpc": "2.0", "id": 2, "method": "tools/call",
         "params": {"name": "lldb_command", "arguments": {"command": command}}}
    ]
    responses, err, rc = drive(args, msgs)
    r = find_response(responses, 2)
    text = text_of(r) if r else ""
    ok = expected_substring in text
    snippet = text.replace("\n", " | ")[:120] if text else "(no response)"
    record(name, ok, snippet)


def test_sos_eeversion_docker():
    sos_check("[docker] SOS eeversion returns runtime version",
              COMMON_ARGS, "eeversion", "SOS Version")


def test_sos_clrthreads_docker():
    sos_check("[docker] SOS clrthreads finds the exception thread",
              COMMON_ARGS, "clrthreads", "InvalidOperationException")


def test_sos_pe_docker():
    sos_check("[docker] SOS pe returns the exception with message",
              COMMON_ARGS, "pe", "mandatoryTag must not be null")


def test_sos_clrstack_docker_with_source():
    sos_check("[docker] SOS clrstack returns frames WITH source file/line",
              COMMON_ARGS, "clrstack", "Program.cs @ 33")


def test_sos_clrmodules_docker():
    sos_check("[docker] SOS clrmodules lists managed modules",
              COMMON_ARGS, "clrmodules", "System.Private.CoreLib")


def test_sos_dumpheap_stat_docker():
    sos_check("[docker] SOS dumpheap -stat shows heap types",
              COMMON_ARGS, "dumpheap -stat", "System.Byte[]")


def test_target_info_docker():
    name = "[docker] target_info reports transport + lldb + dump"
    msgs = initialize_seq() + [
        {"jsonrpc": "2.0", "id": 2, "method": "tools/call",
         "params": {"name": "target_info", "arguments": {}}}
    ]
    responses, _, _ = drive(COMMON_ARGS, msgs)
    r = find_response(responses, 2)
    text = text_of(r) if r else ""
    ok = ("docker" in text and "lldb version" in text and "/work/dump.core" in text
          and "libsosplugin" not in text.lower() or "lldbinit_loads_sos" in text)
    # be lenient — check for transport, lldb version, dump path
    ok = "docker" in text and "lldb version" in text and "/work/dump.core" in text
    record(name, ok, text[:120].replace("\n", " | "))


def test_stateful_thread_select_docker():
    name = "[docker] stateful session: thread select 8 then clrstack shows that thread"
    msgs = initialize_seq() + [
        {"jsonrpc": "2.0", "id": 2, "method": "tools/call",
         "params": {"name": "lldb_command", "arguments": {"command": "thread select 8"}}},
        {"jsonrpc": "2.0", "id": 3, "method": "tools/call",
         "params": {"name": "lldb_command", "arguments": {"command": "clrstack"}}},
    ]
    responses, _, _ = drive(COMMON_ARGS, msgs)
    r = find_response(responses, 3)
    text = text_of(r) if r else ""
    # Thread 8 is the Finalizer in our dump; clrstack on it should NOT mention DoWork (the main thread's frame)
    # but should mention an OS Thread Id different from the main thread (0x94b).
    ok = "OS Thread Id" in text and "0x94b" not in text
    record(name, ok, text[:120].replace("\n", " | "))


def test_copy_dump_docker():
    name = "[docker] --copy-dump pushes local dump to target"
    target_path = "/tmp/copied-dump.core"
    # cleanup any prior file
    docker_run("exec", CONTAINER, "rm", "-f", target_path)
    args = ["--docker", CONTAINER, "--copy-dump",
            "--dump", DUMP_LOCAL, "--target-dump-path", target_path,
            "--exec", "/work/app/Crasher"]
    msgs = initialize_seq() + [
        {"jsonrpc": "2.0", "id": 2, "method": "tools/call",
         "params": {"name": "lldb_command", "arguments": {"command": "eeversion"}}}
    ]
    responses, err, rc = drive(args, msgs)
    r = find_response(responses, 2)
    text = text_of(r) if r else ""
    # File should now exist on target AND lldb should have analyzed it
    rc_check = docker_run("exec", CONTAINER, "test", "-f", target_path)
    ok = rc_check.returncode == 0 and "SOS Version" in text
    record(name, ok, f"file_exists={rc_check.returncode == 0}, sos_ok={'SOS Version' in text}")


# ============================================================================
# Tests — SSH transport
# ============================================================================

SSH_ARGS = ["--ssh", SSH_HOST,
            "--dump", "/tmp/netcore-lldb-test/dump.core",
            "--exec", "/tmp/netcore-lldb-test/app/Crasher"]


def test_sos_eeversion_ssh():
    sos_check("[ssh] SOS eeversion returns runtime version",
              SSH_ARGS, "eeversion", "SOS Version")


def test_sos_pe_ssh():
    sos_check("[ssh] SOS pe returns the exception with message",
              SSH_ARGS, "pe", "mandatoryTag must not be null")


def test_sos_clrstack_ssh_with_source():
    sos_check("[ssh] SOS clrstack returns frames WITH source file/line",
              SSH_ARGS, "clrstack", "Program.cs @ 33")


def test_target_info_ssh():
    name = "[ssh] target_info reports ssh transport"
    msgs = initialize_seq() + [
        {"jsonrpc": "2.0", "id": 2, "method": "tools/call",
         "params": {"name": "target_info", "arguments": {}}}
    ]
    responses, _, _ = drive(SSH_ARGS, msgs)
    r = find_response(responses, 2)
    text = text_of(r) if r else ""
    ok = "ssh" in text and "lldb version" in text
    record(name, ok, text[:120].replace("\n", " | "))


# ============================================================================
# Tests — extended coverage
# ============================================================================

SOS_LOAD_FAIL_MARKERS = (
    "is not a valid command",       # SOS plugin not loaded
    "Failed to find runtime module", # runtime not loaded
    "Can not load or initialize",   # DAC won't load
)


def sos_responded_coherently(text: str) -> bool:
    """True if SOS produced output AND didn't report a setup-level failure."""
    return bool(text) and not any(m in text for m in SOS_LOAD_FAIL_MARKERS)


def test_more_sos_commands_docker():
    """Exercise SOS commands beyond the headline four — broader sanity check.
    For each, we assert SOS responded coherently (no setup failures). The
    specific content depends on what's actually in the dump (e.g. `threadpool`
    legitimately reports "Failed to obtain ThreadPool data." for dumps where
    the pool was never used)."""
    cmds = ["clrstack -a", "clrstack -all", "dso", "eeheap -gc",
            "threadpool", "dumpasync", "gcheapstat"]
    msgs = initialize_seq() + [
        {"jsonrpc": "2.0", "id": 2 + i, "method": "tools/call",
         "params": {"name": "lldb_command", "arguments": {"command": cmd}}}
        for i, cmd in enumerate(cmds)
    ]
    responses, _, _ = drive(COMMON_ARGS, msgs, timeout=180)
    for i, cmd in enumerate(cmds):
        r = find_response(responses, 2 + i)
        text = text_of(r) if r else ""
        ok = sos_responded_coherently(text)
        record(f"[docker] SOS {cmd} responds coherently", ok, text[:80].replace("\n", " | "))


def test_clrstack_flags_argument_handling():
    name = "[docker] command with multi-word args ('thread select 8 ; clrstack') survives shell parsing"
    msgs = initialize_seq() + [
        {"jsonrpc": "2.0", "id": 2, "method": "tools/call",
         "params": {"name": "lldb_command", "arguments": {"command": "thread select 1"}}},
        {"jsonrpc": "2.0", "id": 3, "method": "tools/call",
         "params": {"name": "lldb_command", "arguments": {"command": "clrstack -a"}}},
    ]
    responses, _, _ = drive(COMMON_ARGS, msgs)
    r = find_response(responses, 3)
    text = text_of(r) if r else ""
    ok = "Program.cs @ 33" in text and "PARAMETERS" in text.upper()
    record(name, ok, text[:120].replace("\n", " | "))


def test_large_output_dumpheap_full():
    """`dumpheap -stat` produces a few thousand lines; prompt detection must not get lost in big output."""
    name = "[docker] large output (dumpheap -stat full) doesn't break prompt detection"
    msgs = initialize_seq() + [
        {"jsonrpc": "2.0", "id": 2, "method": "tools/call",
         "params": {"name": "lldb_command", "arguments": {"command": "dumpheap -stat"}}},
        # second call after large output: state must be intact
        {"jsonrpc": "2.0", "id": 3, "method": "tools/call",
         "params": {"name": "lldb_command", "arguments": {"command": "eeversion"}}},
    ]
    responses, _, _ = drive(COMMON_ARGS, msgs, timeout=180)
    big = find_response(responses, 2)
    eev = find_response(responses, 3)
    big_text = text_of(big) if big else ""
    eev_text = text_of(eev) if eev else ""
    ok = ("System.Byte[]" in big_text and len(big_text) > 1000
          and "SOS Version" in eev_text)
    record(name, ok, f"dumpheap={len(big_text)} chars, eeversion_ok={'SOS Version' in eev_text}")


def test_invalid_sos_arg_returns_error_text():
    name = "[docker] invalid SOS argument returns a non-fatal error in the tool output"
    msgs = initialize_seq() + [
        {"jsonrpc": "2.0", "id": 2, "method": "tools/call",
         "params": {"name": "lldb_command", "arguments": {"command": "dumpobj 0xdeadbeef"}}},
        # session still usable after a bad command:
        {"jsonrpc": "2.0", "id": 3, "method": "tools/call",
         "params": {"name": "lldb_command", "arguments": {"command": "eeversion"}}},
    ]
    responses, _, _ = drive(COMMON_ARGS, msgs)
    r2 = find_response(responses, 2)
    r3 = find_response(responses, 3)
    bad = text_of(r2) if r2 else ""
    eev = text_of(r3) if r3 else ""
    # bad command shouldn't kill the session
    ok = "SOS Version" in eev
    record(name, ok, f"after bad command, eeversion ok: {'SOS Version' in eev}")


def test_lldbinit_sos_load_reported():
    name = "[docker] target_info includes lldbinit_loads_sos = True"
    msgs = initialize_seq() + [
        {"jsonrpc": "2.0", "id": 2, "method": "tools/call",
         "params": {"name": "target_info", "arguments": {}}}
    ]
    responses, _, _ = drive(COMMON_ARGS, msgs)
    r = find_response(responses, 2)
    text = text_of(r) if r else ""
    ok = "lldbinit_loads_sos: True" in text
    record(name, ok, text[:200].replace("\n", " | "))


def test_copy_dump_with_default_target_path():
    name = "[docker] --copy-dump without --target-dump-path uses default /tmp/netcore-lldb-dump-*"
    args = ["--docker", CONTAINER, "--copy-dump",
            "--dump", DUMP_LOCAL,
            "--exec", "/work/app/Crasher"]
    msgs = initialize_seq() + [
        {"jsonrpc": "2.0", "id": 2, "method": "tools/call",
         "params": {"name": "target_info", "arguments": {}}}
    ]
    responses, err, _ = drive(args, msgs)
    r = find_response(responses, 2)
    text = text_of(r) if r else ""
    ok = "/tmp/netcore-lldb-dump-" in text
    record(name, ok, text[:200].replace("\n", " | "))


def test_concurrent_serialization():
    """Rapid successive calls — verifies the LldbSession lock prevents output tangling."""
    name = "[docker] rapid successive lldb_command calls all roundtrip correctly"
    cmds = ["eeversion", "clrthreads", "pe", "clrstack", "eeversion",
            "clrmodules", "pe", "clrthreads"]
    msgs = initialize_seq() + [
        {"jsonrpc": "2.0", "id": 10 + i, "method": "tools/call",
         "params": {"name": "lldb_command", "arguments": {"command": c}}}
        for i, c in enumerate(cmds)
    ]
    responses, _, _ = drive(COMMON_ARGS, msgs, timeout=180)
    ok_count = 0
    for i, c in enumerate(cmds):
        r = find_response(responses, 10 + i)
        if r and not r.get("result", {}).get("isError", False):
            ok_count += 1
    ok = ok_count == len(cmds)
    record(name, ok, f"{ok_count}/{len(cmds)} succeeded")


def test_bootstrap_installs_lldb_and_sos_on_bare_target():
    """The real customer scenario: their app's container has the .NET runtime
    but not lldb. Verify that `--bootstrap` installs both lldb and the SOS
    debugger extension into a fresh container, and that SOS commands work
    immediately afterward.

    Takes 1-3 minutes the first time (apt-get install + dotnet tool install).
    Re-running against an already-bootstrapped target is fast (idempotent)."""
    name = "[docker/bootstrap] --bootstrap installs lldb+SOS on a target that lacks them"
    bare = "netcore-lldb-bootstrap-test"
    docker_run("rm", "-f", bare)
    rc = subprocess.call([
        "docker", "run", "-d", "--name", bare,
        # Mount the WSL host's actual dotnet install so SOS finds byte-identical
        # runtime binaries when analyzing this fixture's dump. In production the
        # target IS the customer's container, so this match is automatic.
        "-v", "/usr/lib/dotnet:/usr/lib/dotnet:ro",
        "--entrypoint", "sleep",
        "mcr.microsoft.com/dotnet/sdk:10.0-noble", "infinity",
    ], stdout=subprocess.DEVNULL, timeout=60)
    if rc != 0:
        record(name, False, "could not start bare dotnet SDK target")
        return
    try:
        # Symlink the alternate dotnet install path the dump records into the
        # one Docker resolved the bind mount to.
        subprocess.run(["docker", "exec", bare, "sh", "-c",
                        "[ -e /usr/lib/dotnet ] || ln -sf /usr/share/dotnet /usr/lib/dotnet"],
                       capture_output=True, timeout=15)
        # Sanity: confirm lldb is NOT in the bare image before --bootstrap.
        rc, out, _ = (lambda r: (r.returncode, r.stdout, r.stderr))(
            subprocess.run(["docker", "exec", bare, "sh", "-c", "command -v lldb || echo MISSING"],
                           capture_output=True, text=True, timeout=10))
        if "MISSING" not in out:
            record(name, False, f"bare image already had lldb? out={out!r}")
            return

        # Stage the crasher dump + binaries inside the target.
        # Create /work first — the bare SDK image doesn't have it (only our
        # reference image does, via its Dockerfile).
        subprocess.run(["docker", "exec", bare, "mkdir", "-p", "/work/app"],
                       check=True, timeout=15)
        subprocess.run(["docker", "cp", DUMP_LOCAL, f"{bare}:/work/dump.core"],
                       check=True, timeout=60)
        subprocess.run(["docker", "cp", f"{APP_LOCAL}/.", f"{bare}:/work/app/"],
                       check=True, timeout=60)
        # Make the dump's recorded executable path resolve to /work/app/Crasher.
        subprocess.run(["docker", "exec", bare, "bash", "-c",
                        'RECORDED=$(strings /work/dump.core 2>/dev/null | grep -oE "^/[^[:space:]]+/Crasher$" | head -1 || true); '
                        '[ -n "$RECORDED" ] && mkdir -p "$(dirname $RECORDED)" && '
                        'for f in /work/app/*; do ln -sf "$f" "$(dirname $RECORDED)/$(basename $f)"; done'],
                       capture_output=True, timeout=15)

        # Drive the client with --bootstrap and a SOS query in one go.
        args = ["--docker", bare, "--bootstrap",
                "--dump", "/work/dump.core", "--exec", "/work/app/Crasher"]
        msgs = initialize_seq() + [
            {"jsonrpc": "2.0", "id": 2, "method": "tools/call",
             "params": {"name": "lldb_command", "arguments": {"command": "eeversion"}}},
            {"jsonrpc": "2.0", "id": 3, "method": "tools/call",
             "params": {"name": "lldb_command", "arguments": {"command": "pe"}}},
        ]
        responses, err, _ = drive(args, msgs, timeout=600)
        eev = find_response(responses, 2)
        pe = find_response(responses, 3)
        eev_text = text_of(eev) if eev else ""
        pe_text = text_of(pe) if pe else ""
        ok = ("SOS Version" in eev_text
              and "InvalidOperationException" in pe_text
              and "mandatoryTag must not be null" in pe_text)
        note = (f"eeversion sos-ok={'SOS Version' in eev_text}, "
                f"pe matched={'mandatoryTag' in pe_text}, "
                f"stderr tail: {err[-200:].strip() if err else ''}")
        record(name, ok, note)
    finally:
        docker_run("rm", "-f", bare)


def test_bootstrap_idempotent_on_already_setup_target():
    """Running with --bootstrap against a target that already has lldb + SOS
    should be a no-op + a quick verification, not a re-install."""
    name = "[docker/bootstrap] --bootstrap is idempotent (already-installed target stays fast)"
    args = ["--docker", CONTAINER, "--bootstrap",
            "--dump", "/work/dump.core", "--exec", "/work/app/Crasher"]
    msgs = initialize_seq() + [
        {"jsonrpc": "2.0", "id": 2, "method": "tools/call",
         "params": {"name": "lldb_command", "arguments": {"command": "eeversion"}}},
    ]
    start = time.time()
    responses, err, _ = drive(args, msgs, timeout=120)
    elapsed = time.time() - start
    r = find_response(responses, 2)
    text = text_of(r) if r else ""
    # Idempotent fast path: should NOT have re-installed packages.
    ok = ("SOS Version" in text
          and "already present" in err.lower()
          and "already installed and configured" in err.lower()
          and elapsed < 60)
    record(name, ok, f"elapsed={elapsed:.1f}s, sos_ok={'SOS Version' in text}")


def test_bash_wrapper_invocation():
    name = "[docker] bash wrapper (client/netcore-lldb) invokes the python script correctly"
    wrapper = os.path.join(ROOT, "client", "netcore-lldb")
    if not os.path.isfile(wrapper):
        record(name, False, "wrapper not found")
        return
    os.chmod(wrapper, 0o755)
    proc = subprocess.Popen(
        [wrapper, "--docker", CONTAINER,
         "--dump", "/work/dump.core", "--exec", "/work/app/Crasher"],
        stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True,
    )
    msgs = initialize_seq() + [
        {"jsonrpc": "2.0", "id": 2, "method": "tools/call",
         "params": {"name": "lldb_command", "arguments": {"command": "eeversion"}}}
    ]
    inp = "\n".join(json.dumps(m) for m in msgs) + "\n"
    out, err = proc.communicate(input=inp, timeout=90)
    responses = [json.loads(ln) for ln in out.splitlines() if ln.strip()]
    r = find_response(responses, 2)
    text = text_of(r) if r else ""
    ok = "SOS Version" in text
    record(name, ok)


def test_unknown_arg_rejected():
    name = "[common] unknown CLI arg rejected"
    proc = subprocess.run([sys.executable, CLIENT, "--bogus", "x", "--docker", "c", "--dump", "/x"],
                          capture_output=True, text=True)
    ok = proc.returncode != 0 and ("unrecognized" in proc.stderr or "unknown" in proc.stderr.lower())
    record(name, ok)


def test_help_works():
    name = "[common] --help prints usage and exits 0"
    proc = subprocess.run([sys.executable, CLIENT, "--help"], capture_output=True, text=True)
    ok = proc.returncode == 0 and "--docker" in proc.stdout and "--ssh" in proc.stdout
    record(name, ok)


# ============================================================================
# Tests — curated fixture dumps (one per Tess playbook)
# ============================================================================

def fixture_check(name: str, fixture_key: str, command: str,
                  expected_substrings: list[str], any_of: bool = False) -> None:
    """Drive the client (over SSH for path simplicity) against a fixture dump
    and assert the SOS output contains the expected pattern(s).

    `any_of=False` (default) → all substrings must appear.
    `any_of=True`            → at least one must appear."""
    f = FIXTURES.get(fixture_key)
    if not f or not os.path.exists(f["dump"]) or not os.path.exists(f["exec"]):
        record(name, False, f"fixture {fixture_key!r} missing (run tests/fixtures/build-and-dump.sh)")
        return
    args = ["--ssh", SSH_HOST, "--dump", f["dump"], "--exec", f["exec"]]
    msgs = initialize_seq() + [
        {"jsonrpc": "2.0", "id": 2, "method": "tools/call",
         "params": {"name": "lldb_command", "arguments": {"command": command}}}
    ]
    responses, _, _ = drive(args, msgs, timeout=120)
    r = find_response(responses, 2)
    text = text_of(r) if r else ""
    matches = [s for s in expected_substrings if s in text]
    ok = (bool(matches) if any_of else len(matches) == len(expected_substrings))
    snippet = text[:140].replace("\n", " | ")
    note = f"matched {len(matches)}/{len(expected_substrings)}; first line: {snippet}"
    record(name, ok, note)


# --- memory-leak fixture ---------------------------------------------------

def test_fixture_memory_leak_eeheap():
    fixture_check(
        "[fixture/memory-leak] eeheap -gc reports >10 MB managed memory",
        "memory-leak", "eeheap -gc",
        # The fixture allocates 50 × 256 KB = 12.8 MB. eeheap output includes
        # 'GC Allocated Heap Size' line with a hex size; we just check the
        # eeheap output is well-formed and mentions a heap segment.
        ["GC Heap", "Heap"], any_of=True,
    )


def test_fixture_memory_leak_dumpheap():
    fixture_check(
        "[fixture/memory-leak] dumpheap -stat shows System.Byte[] as a top type",
        "memory-leak", "dumpheap -stat",
        ["System.Byte[]"],
    )


def test_fixture_memory_leak_pe():
    fixture_check(
        "[fixture/memory-leak] pe shows the staged retention message",
        "memory-leak", "pe",
        ["InvalidOperationException", "Simulated static-collection retention"],
    )


def test_fixture_memory_leak_clrstack():
    fixture_check(
        "[fixture/memory-leak] clrstack shows MemoryLeakFixture.Program.Main",
        "memory-leak", "clrstack",
        ["MemoryLeakFixture.Program.Main"],
    )


def test_fixture_memory_leak_gcroot_handles_sos_instability():
    """Verify that when SOS's `gcroot` crashes lldb (a known .NET 10 DAC bug
    in libmscordaccore.so), our client tool reports the crash as a tool
    error rather than hanging or leaking state. This protects the LLM
    workflow: it sees `isError: true`, can fall back to other techniques,
    and the next MCP call still works (the next invocation spawns a fresh
    lldb)."""
    name = "[fixture/memory-leak] gcroot SOS instability is surfaced as isError"
    f = FIXTURES["memory-leak"]
    args = ["--ssh", SSH_HOST, "--dump", f["dump"], "--exec", f["exec"]]
    msgs = initialize_seq() + [
        {"jsonrpc": "2.0", "id": 2, "method": "tools/call",
         "params": {"name": "lldb_command",
                    "arguments": {"command": "dumpheap -type System.Byte[] -min 200000"}}},
        {"jsonrpc": "2.0", "id": 3, "method": "tools/call",
         "params": {"name": "lldb_command",
                    "arguments": {"command": "gcroot 7f000000abcd"}}},
    ]
    responses, _, _ = drive(args, msgs, timeout=120)
    # dumpheap should succeed (msg 2). gcroot may either succeed OR crash;
    # if it crashes, the result must be reported as isError, NOT a hang.
    r2 = find_response(responses, 2)
    r3 = find_response(responses, 3)
    dumpheap_ok = r2 and not r2.get("result", {}).get("isError")
    gcroot_handled = bool(r3)  # we got SOME response (success or isError) — never a hang
    ok = bool(dumpheap_ok and gcroot_handled)
    note = (f"dumpheap_ok={bool(dumpheap_ok)}, "
            f"gcroot_response_received={bool(r3)}, "
            f"gcroot_isError={r3 and r3.get('result', {}).get('isError', False) if r3 else 'n/a'}")
    record(name, ok, note)


# --- deadlock fixture ------------------------------------------------------

def test_fixture_deadlock_clrthreads():
    fixture_check(
        "[fixture/deadlock] clrthreads shows three managed threads",
        "deadlock", "clrthreads",
        ["ThreadCount:"],
    )


def test_fixture_deadlock_syncblk():
    fixture_check(
        "[fixture/deadlock] syncblk reveals lock contention",
        "deadlock", "syncblk",
        ["MonitorHeld", "Owning Thread Info"], any_of=True,
    )


def test_fixture_deadlock_pe():
    fixture_check(
        "[fixture/deadlock] pe shows the TimeoutException with deadlock message",
        "deadlock", "pe",
        ["TimeoutException", "deadlocked"],
    )


def test_fixture_deadlock_clrstack_all():
    fixture_check(
        "[fixture/deadlock] clrstack -all surfaces Monitor.* on worker threads",
        "deadlock", "clrstack -all",
        ["Monitor", "DeadlockFixture.Program"], any_of=False,
    )


# --- event-handler-leak fixture --------------------------------------------

def test_fixture_event_handler_dumpheap():
    fixture_check(
        "[fixture/event-handler-leak] dumpheap -stat shows Subscriber instances",
        "event-handler-leak", "dumpheap -stat",
        ["EventHandlerLeakFixture.Subscriber"],
    )


def test_fixture_event_handler_subscribers_count():
    """Pull instance count from `dumpheap -type Subscriber` — should be 100."""
    name = "[fixture/event-handler-leak] 100 Subscriber instances on heap"
    f = FIXTURES["event-handler-leak"]
    args = ["--ssh", SSH_HOST, "--dump", f["dump"], "--exec", f["exec"]]
    msgs = initialize_seq() + [
        {"jsonrpc": "2.0", "id": 2, "method": "tools/call",
         "params": {"name": "lldb_command",
                    "arguments": {"command": "dumpheap -type EventHandlerLeakFixture.Subscriber"}}}
    ]
    responses, _, _ = drive(args, msgs, timeout=120)
    r = find_response(responses, 2)
    text = text_of(r) if r else ""
    m = re.search(r"Total\s+(\d+)\s+objects", text)
    count = int(m.group(1)) if m else 0
    ok = count >= 100
    record(name, ok, f"Subscriber count: {count}")


def test_fixture_event_handler_alt_retention_evidence():
    """gcroot crashes on .NET 10 dumps — see the memory-leak fixture test
    for the workaround. But we can still PROVE the event-handler leak from
    the heap: there should be MulticastDelegate / EventHandler instances on
    the heap (one per subscription), exactly mirroring the Subscriber count.
    That's a strong-enough signal that the LLM can reason about retention."""
    name = "[fixture/event-handler-leak] delegate instances on heap mirror Subscriber count"
    f = FIXTURES["event-handler-leak"]
    args = ["--ssh", SSH_HOST, "--dump", f["dump"], "--exec", f["exec"]]
    msgs = initialize_seq() + [
        {"jsonrpc": "2.0", "id": 2, "method": "tools/call",
         "params": {"name": "lldb_command",
                    "arguments": {"command": "dumpheap -type System.EventHandler"}}}
    ]
    responses, _, _ = drive(args, msgs, timeout=120)
    r = find_response(responses, 2)
    text = text_of(r) if r else ""
    m = re.search(r"Total\s+(\d+)\s+objects", text)
    count = int(m.group(1)) if m else 0
    # Each Publisher.Tick += sub.OnTick allocates an EventHandler delegate.
    # 100 subscriptions → at least ~100 EventHandler instances (often more
    # because each += clones the multicast list).
    ok = count >= 100
    record(name, ok, f"EventHandler instances on heap: {count}")


# ============================================================================
# Main
# ============================================================================

def main() -> int:
    print(f"client:  {CLIENT}")
    print(f"dump:    {DUMP_LOCAL}")
    print(f"app:     {APP_LOCAL}")
    print()

    print("--- setting up targets ---")
    setup_docker_target()
    setup_ssh_target()

    try:
        print("\n--- arg / preflight tests ---")
        test_args_no_transport()
        test_args_both_transports()
        test_args_missing_dump()
        test_args_copy_dump_local_missing()
        test_preflight_bad_container()
        test_preflight_bad_ssh()
        test_preflight_no_lldb()
        test_preflight_missing_dump()

        print("\n--- MCP protocol tests ---")
        test_mcp_initialize()
        test_mcp_tools_list()
        test_mcp_ping()
        test_mcp_unknown_method()
        test_mcp_unknown_tool()
        test_mcp_bad_command_arg()

        print("\n--- MCP resources + prompts (Phases 1 & 2) ---")
        test_mcp_initialize_advertises_resources_and_prompts()
        test_resources_list_returns_playbooks_and_state()
        test_resources_read_playbook_crash()
        test_resources_read_session_returns_json()
        test_resources_read_modules_runs_clrmodules()
        test_resources_read_threads_runs_clrthreads()
        test_resources_read_unknown_uri_returns_invalid_params()
        test_prompts_list_returns_scenario_prompts()
        test_prompts_get_analyze_memory_references_memory_playbook()
        test_prompts_get_overview_no_playbook()
        test_prompts_get_unknown_returns_invalid_params()

        print("\n--- SOS via docker exec ---")
        test_sos_eeversion_docker()
        test_sos_clrthreads_docker()
        test_sos_pe_docker()
        test_sos_clrstack_docker_with_source()
        test_sos_clrmodules_docker()
        test_sos_dumpheap_stat_docker()
        test_target_info_docker()
        test_stateful_thread_select_docker()
        test_copy_dump_docker()

        print("\n--- SOS via ssh ---")
        test_sos_eeversion_ssh()
        test_sos_pe_ssh()
        test_sos_clrstack_ssh_with_source()
        test_target_info_ssh()

        print("\n--- extended coverage ---")
        test_help_works()
        test_unknown_arg_rejected()
        test_lldbinit_sos_load_reported()
        test_more_sos_commands_docker()
        test_clrstack_flags_argument_handling()
        test_invalid_sos_arg_returns_error_text()
        test_large_output_dumpheap_full()
        test_copy_dump_with_default_target_path()
        test_concurrent_serialization()
        test_bash_wrapper_invocation()
        test_bootstrap_idempotent_on_already_setup_target()
        test_bootstrap_installs_lldb_and_sos_on_bare_target()

        print("\n--- curated fixture dumps (one per Tess playbook) ---")
        # Memory leak (static-collection retention)
        test_fixture_memory_leak_eeheap()
        test_fixture_memory_leak_dumpheap()
        test_fixture_memory_leak_pe()
        test_fixture_memory_leak_clrstack()
        test_fixture_memory_leak_gcroot_handles_sos_instability()
        # Deadlock (lock-order inversion)
        test_fixture_deadlock_clrthreads()
        test_fixture_deadlock_syncblk()
        test_fixture_deadlock_pe()
        test_fixture_deadlock_clrstack_all()
        # Event-handler leak
        test_fixture_event_handler_dumpheap()
        test_fixture_event_handler_subscribers_count()
        test_fixture_event_handler_alt_retention_evidence()
    finally:
        teardown_docker_target()

    print("\n==================== SUMMARY ====================")
    total = len(results)
    passed = sum(1 for _, ok, _ in results if ok)
    failed = total - passed
    for name, ok, note in results:
        mark = "PASS" if ok else "FAIL"
        color = "\033[32m" if ok else "\033[31m"
        print(f"  {color}{mark}\033[0m  {name}")
        if not ok and note:
            print(f"           note: {note}")
    print(f"\n{passed}/{total} passed, {failed} failed")
    return 0 if failed == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
